theme: minima
title: Portfolio
description: A portfolio site
markdown: kramdown

# Navigation links
nav:
  - title: "About Me"
    url: "/index.html"
  - title: "Projects"
    url: "/projects.html"
